name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

# Cancel in progress workflows
# in the scenario where we already had a run going for that PR/branch/tag but then triggered a new run
concurrency:
  group: "${{ github.workflow }} ✨ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install --ignore-scripts --include=dev

      - name: Run lint
        run: npm run lint

  performance:
    name: Run performance test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run performance test
        run: npm run test:performance

  test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version:
          - "0.10"
          - "0.12"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
          - "21"
          - "22"
          - "23"
          - "24"
        # Use supported versions of our testing tools under older versions of Node
        # Install npm in some specific cases where we need to
        include:
          - node-version: "0.10"
            npm-i: "mocha@3.5.3 nyc@10.3.2 supertest@2.0.0"
            # Npm isn't being installed on windows w/ setup-node for
            # 0.10 and 0.12, which will end up choking when npm uses es6
            npm-version: "npm@2.15.1"
            npm-rm: 'iconv'

          - node-version: "0.12"
            npm-i: "mocha@3.5.3 nyc@10.3.2"
            npm-version: "npm@2.15.11"
            npm-rm: 'iconv'

          - node-version: "4"
            npm-i: "mocha@5.2.0 nyc@11.9.0"
            npm-rm: 'iconv'

          - node-version: "5"
            npm-i: "mocha@5.2.0 nyc@11.9.0"
            # fixes https://github.com/npm/cli/issues/681
            npm-version: "npm@3.10.10"
            npm-rm: 'iconv'

          - node-version: "6"
            npm-i: "mocha@6.2.2 nyc@14.1.1"
            npm-rm: 'iconv'

          - node-version: "7"
            npm-i: "mocha@6.2.2 nyc@14.1.1"
            npm-rm: 'iconv'

          - node-version: "8"
            npm-i: "mocha@7.2.0 nyc@14.1.1"
            npm-rm: 'iconv'

          - node-version: "9"
            npm-i: "mocha@7.2.0 nyc@14.1.1"
            npm-rm: 'iconv'

          - node-version: "10"
            npm-i: "mocha@8.4.0"
            npm-rm: 'iconv'

          - node-version: "11"
            npm-i: "mocha@8.4.0"
            npm-rm: 'iconv'

          - node-version: "12"
            npm-i: "mocha@9.2.2"
            npm-rm: 'iconv'

          - node-version: "13"
            npm-i: "mocha@9.2.2"
            npm-rm: 'iconv'

          - node-version: "14"
            npm-rm: 'iconv'

          - node-version: "15"
            npm-rm: 'iconv'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm version fixes
        if: ${{matrix.npm-version != ''}}
        run: npm install -g ${{ matrix.npm-version }}

      - name: Configure npm loglevel
        run: |
          npm config set loglevel error
        shell: bash

      - name: Remove npm module(s) ${{ matrix.npm-rm }}
        run: npm rm --silent --save-dev ${{ matrix.npm-rm }}
        if: matrix.npm-rm != ''

      - name: Install Node version specific dev deps
        if: ${{ matrix.npm-i != '' }}
        run: npm install --save-dev ${{ matrix.npm-i }}

      - name: Install dependencies
        run: npm install

      - name: Output Node and NPM versions
        run: |
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"

      - name: Run tests
        shell: bash
        run: npm run test:ci

      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-node-${{ matrix.node-version }}-${{ matrix.os }}
          path: ./coverage/lcov.info
          retention-days: 1
                
  coverage:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Install lcov
        shell: bash
        run: sudo apt-get -y install lcov

      - name: Collect coverage reports
        uses: actions/download-artifact@v5
        with:
          path: ./coverage
          pattern: coverage-node-*

      - name: Merge coverage reports
        shell: bash
        run: find ./coverage -name lcov.info -exec printf '-a %q\n' {} \; | xargs lcov -o ./lcov.info

      - name: Upload coverage report
        uses: coverallsapp/github-action@v2
        with:
          file: ./lcov.info

  test_webpack:
    name: Run tests webpack
    strategy:
      fail-fast: false
      matrix:
        node-version: ["12", "*"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Webpack test
        shell: bash
        run: |
          npm run test:webpack